use_frameworks!

platform :ios, '10.0'

target 'DAOBottomSheet_Example' do
  pod 'DAOBottomSheet', :path => '../'
  pod 'SnapKit', '~> 5.0.0'

  target 'DAOBottomSheet_Tests' do
    inherit! :search_paths

    
  end
end
